apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-application
  template:
    metadata:
      labels:
        app: mlops-application
    spec:
      containers:
      - name: mlops-application
        image: saadmohamedamine/mlops-project:latest
        ports:
        - containerPort: 5000